name: CMake Multi-Platform CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    timeout-minutes: 360
    #concurrency:
     # group: ${{ github.workflow }}-${{ github.ref }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Release]
        include:
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
            build_type: Release
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
            build_type: Release
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++
            build_type: Release

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive  

      - name: Configure CMake
        run: |
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        env:
          CC: ${{ matrix.c_compiler }}
          CXX: ${{ matrix.cpp_compiler }}

      - name: Build
        run: cmake --cmake-build-debug ${{github.workspace}}/cmake-build-debug --config ${{ matrix.build_type }}

      - name: Test
        working-directory: ${{github.workspace}}/cmake-build-debug
        run: |
            ctest -C ${{ matrix.build_type }} --output-on-failure
        if: ${{ success() }}

      - name: Install
        if: ${{ success() && matrix.build_type == 'Release' }}
        run: |
          cmake --install ${{github.workspace}}/build --prefix ${{github.workspace}}/install
      - name: Upload cmake-build-debug artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lm-cmake-build-debug-${{ matrix.os }}-run${{ github.run_id }}
          path: 
            ${{ github.workspace }}/cmake-build-debug/bin
            ${{ github.workspace }}/cmake-build-debug/lib/
          retention-days: 7
        if: ${{ success() && matrix.os != 'windows-latest' }}
      - name: Upload artifacts for Windows
        uses: actions/upload-artifact@v4
        with:
          name: lm-cmake-build-debug-${{ matrix.os }}-run${{ github.run_id }}
          path: |
            ${{ github.workspace }}/build/bin/
          retention-days: 7
        if: ${{ success() && matrix.os == 'windows-latest' }}
