name: CMake Multi-Platform CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    timeout-minutes: 360
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Release, Debug]
        include:
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: windows-latest
            build_type: Debug  # Windows上不测试Debug

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up environment
        run: |
          echo "CC=${{ matrix.c_compiler }}" >> $GITHUB_ENV
          echo "CXX=${{ matrix.cpp_compiler }}" >> $GITHUB_ENV

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev libxi-dev

      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install glfw3

      - name: Configure CMake
        run: |
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{ matrix.build_type }}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{ matrix.build_type }} --output-on-failure

      - name: Install
        run: |
          cmake --install ${{github.workspace}}/build --prefix install
      - name: CMake Action
        # You may pin to the exact commit or the version.
        # uses: threeal/cmake-action@725d1314ccf9ea922805d7e3f9d9bcbca892b406
        uses: threeal/cmake-action@v2.1.0
        with:
    # The build directory of the CMake project
          build-dir: build
    # The preferred executable for compiling C language files
          c-compiler: gcc
    # The preferred executable for compiling C++ language files
          cxx-compiler: g++
    # Additional flags to pass when compiling C language files
          c-flags: -O3 -g0 -flto
    # Additional flags to pass when compiling C++ language files
          cxx-flags: -O3 -g0 -flto -std=c++23
